/*
 * This source file was generated by the Gradle 'init' task
 */
package ca.antany.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertDoesNotThrow(()->new App());
        assertDoesNotThrow(()->App.main(null));
    }
}
